site_name: Django Simple API
site_description: A non-intrusive component that can help you quickly create APIs.

repo_name: django-simple-api
repo_url: https://github.com/Django-Simple-API/django-simple-api
edit_uri: https://github.com/Django-Simple-API/django-simple-api/tree/master/docs/

use_directory_urls: true

theme:
  name: "material"
  language: "en"
  palette:
    scheme: default
    primary: blue
  feature:
    tabs: true

nav:
  - 首页: "index.md"
  - 快速开始: "quick-start.md"
  - 参数声明: "declare-parameters.md"
  - 参数校验: "parameter-verification.md"
  - 文档生成: "document-generation.md"
  - 扩展功能: "extensions-function.md"

markdown_extensions:
  - admonition
  - extra
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
